export const VIEWPORT = {
    CANVAS_WIDTH: 600,
    CANVAS_HEIGHT: 400,
} as const;

export const TARGET = {
    WIDTH: 64,
    HEIGHT: 36,
} as const;

export const CONSTANTS = {
    DIGIT_COUNT: 8,
    TICK_RATE_MS: 100,
    STARTING_TARGET_SPEED: 4,
    MAX_TARGET_SPEED: 10,
    TICKS_TO_MAX_SPEED: 1200,
    MIN_TARGET_SPAWN_MS: 1000,
    MAX_TARGET_SPAWN_MS: 3000,
    MAX_TARGET_VALUE: 0xff,
    CHECK_LINE_Y: 300,
    MIN_SCORE_CHALLENGE: 8,
    MAX_SCORE_CHALLENGE: 12,
    MIN_FAST_TARGETS: 3,
    MAX_FAST_TARGETS: 6,
    MIN_FAST_SECONDS: 12,
    MAX_FAST_SECONDS: 20,
    MIN_FLAWLESS_SCORE: 15,
    MAX_FLAWLESS_SCORE: 25,
} as const;
